POST http://localhost:3003/login/
Content-Type: application/json

{
    "username": "kalpana",
    "password": "1234"
}
###

POST http://localhost:3003/signup/
Content-Type: application/json

{
    "username": "kalpana",
    "password": "2112",
    "name": "Kalpana",
    "age": 50,
    "gender": "female"
}
###

GET http://localhost:3003/users/
###

GET http://localhost:3003/users/5/
###

PUT  http://localhost:3003/users/modify/5/
Content-Type: application/json

{
    "password": "1234",
    "name": "Kalpana",
    "age": 44,
    "gender": "female"
}
###